# Generated by Django 4.1 on 2022-09-27 10:17

import Busticket.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.IntegerField()),
                ('expiry', models.CharField(default=None, max_length=30)),
                ('cvv', models.IntegerField()),
                ('balance', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('bid', models.AutoField(primary_key=True, serialize=False)),
                ('btype', models.CharField(max_length=100)),
                ('bno', models.CharField(max_length=100, unique=True)),
                ('seats', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Bus_Schedule',
            fields=[
                ('bsc_id', models.AutoField(primary_key=True, serialize=False)),
                ('deptime', models.CharField(max_length=100)),
                ('arrivaltime', models.CharField(max_length=100)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Busticket.bus')),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('did', models.AutoField(primary_key=True, serialize=False)),
                ('dname', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('logid', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('rid', models.AutoField(primary_key=True, serialize=False)),
                ('fromlocation', models.CharField(max_length=100)),
                ('tolocation', models.CharField(max_length=100)),
                ('rmap', models.ImageField(upload_to=Busticket.models.get_file_path)),
            ],
        ),
        migrations.CreateModel(
            name='Seat_Schedule',
            fields=[
                ('seatid', models.AutoField(primary_key=True, serialize=False)),
                ('schedule_date', models.CharField(max_length=100)),
                ('available_seat', models.IntegerField()),
                ('bus_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Busticket.bus_schedule')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(default=None, max_length=100)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('dob', models.CharField(max_length=100)),
                ('phone', models.BigIntegerField()),
                ('address', models.CharField(max_length=300)),
                ('gender', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to=Busticket.models.get_file_path)),
                ('login', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Busticket.login')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(default=None, max_length=100)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('dob', models.CharField(max_length=100)),
                ('phone', models.BigIntegerField()),
                ('ustatus', models.CharField(default='waiting', max_length=100)),
                ('login', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Busticket.login')),
            ],
        ),
        migrations.CreateModel(
            name='Ticketrate',
            fields=[
                ('ticket_id', models.AutoField(primary_key=True, serialize=False)),
                ('adult', models.IntegerField()),
                ('child', models.IntegerField()),
                ('bustype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Busticket.bus')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Busticket.route')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticid', models.AutoField(primary_key=True, serialize=False)),
                ('pas', models.IntegerField()),
                ('adult', models.IntegerField()),
                ('child', models.IntegerField()),
                ('tot', models.IntegerField()),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Busticket.seat_schedule')),
                ('uname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Busticket.user')),
            ],
        ),
        migrations.CreateModel(
            name='Staffallot',
            fields=[
                ('allot_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=10)),
                ('bus_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Busticket.bus_schedule')),
                ('schedule_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Busticket.seat_schedule')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Busticket.staff')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('lid', models.AutoField(primary_key=True, serialize=False)),
                ('lname', models.CharField(max_length=100, unique=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Busticket.district')),
            ],
        ),
        migrations.AddField(
            model_name='bus_schedule',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Busticket.route'),
        ),
    ]
